### ISSUE TITLE
帅

### ISSUE THREAD

**Issue by iMayday-Yee** [ArchLance/Neptune-web#1]
你怎么也开始vue了

**Comment by ArchLance** [comment]
不star?



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2024年08月28日 16:15 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***> |
| 主题 | [ArchLance/Neptune-web] 帅 (Issue #1) |

你怎么也开始vue了

**Comment by iMayday-Yee** [comment]
包star的
